/**
 * @froglight/foundation — portable workspace/capability contracts.
 *
 * The runtime kernel stays product-free. This package owns host-independent
 * storage, document, workspace, search, navigation, editor-registry, and
 * related capability contracts; concrete host/editor providers live elsewhere.
 */

// Paths and identity.
export {
  ROOT_PATH,
  isValidWorkspacePath,
  isValidSegment,
  workspacePath,
  isWorkspacePath,
  assertWorkspacePath,
  parsePath,
  isRootPath,
  joinPath,
  parentPath,
  pathName,
  pathDepth,
  isWithinPath,
  type WorkspacePath,
} from './paths.js';
export {
  resourceId,
  documentId,
  documentKindId,
  generateResourceId,
  generateDocumentId,
  type ResourceId,
  type DocumentId,
  type DocumentKindId,
} from './identity.js';

// Errors.
export {
  ErrorCodes,
  FroglightError,
  VaultError,
  ServiceDisposedError,
  isFroglightError,
  isVaultError,
  isVaultErrorCode,
  toStructuredError,
  type VaultErrorCode,
  type ErrorCode,
} from './errors.js';

// Records.
export {
  parseVersionedRecord,
  serializeVersionedRecord,
  stableStringify,
  pickUnknown,
  type VersionedRecord,
} from './records.js';

// Vault contract + providers.
export {
  type VaultOperation,
  type PathCaseSensitivity,
  type NameNormalization,
  type VaultCapabilities,
  type VaultEntry,
  type VaultStat,
  type VaultOperationOptions,
  type VaultService,
} from './vault/contract.js';
export { ensureDirectory, isAlreadyExists } from './vault/helpers.js';
export {
  exportVaultBackup,
  restoreVaultBackup,
  type VaultBackupExport,
  type VaultBackupExportProgress,
  type VaultBackupRestorePhase,
  type VaultBackupRestoreComplete,
  type VaultBackupRestorePartial,
  type VaultBackupRestoreResult,
} from './vault/backup.js';
export {
  createMemoryVaultState,
  createMemoryVault,
  MemoryVault,
  type MemoryVaultState,
  type MemoryVaultOptions,
  type VaultFailureInjector,
} from './vault/memory.js';
export {
  createVaultContractSuite,
  SuiteAssertionError,
  assertTrue,
  assertEqual,
  assertBytesEqual,
  assertVaultError,
  type VaultContractCase,
  type VaultContractSuiteOptions,
} from './vault/contract-suite.js';

// Documents and identity records.
export {
  InMemoryDocumentRegistry,
  DOCUMENT_CONTENT_REVISION_KEY,
  DEFAULT_DOCUMENT_PRESENTATION_MODES,
  cloneTemplateValue,
  type DocumentPresentationMode,
  newDocumentId,
  newResourceId,
  refFor,
  locationFor,
  resolvePathFor,
  type DocumentLocation,
  type DocumentRef,
  type DecodedDocument,
  type DocumentRecoveryWarning,
  type DocumentKindDescriptor,
  type DocumentRegistry,
  type Disposer,
} from './documents.js';
export {
  InMemoryDocumentPresentationRegistry,
  type DocumentPresentation,
  type DocumentPresentationRegistry,
} from './document-presentation.js';
export {
  updateDocumentTitle,
  DocumentTitleUnavailableError,
  type DocumentTitleUnavailableReason,
  type DocumentTitleUpdateResult,
} from './document-titles.js';

// Derived state services.
export {
  InMemoryMetadataService,
  type JsonValue,
  type NormalizedMetadata,
  type MetadataService,
} from './metadata.js';
export {
  InMemoryRelationshipService,
  type Relationship,
  type RelationshipInput,
  type RelationshipService,
} from './relationships.js';
export {
  InMemoryCommandService,
  type Command,
  type CommandResult,
  type CommandService,
} from './commands.js';
export {
  InMemorySettingsService,
  isValidSettingsKey,
  assertSettingsKey,
  type SettingsService,
  type SettingsValue,
} from './settings.js';
export {
  PersistentSettingsService,
  PERSISTENT_SETTINGS_STORAGE_KEY,
  PERSISTENT_SETTINGS_VERSION,
  type PersistentSettingsStorage,
} from './settings-persistent.js';
export {
  InMemoryNavigationService,
  type NavigationEntry,
  type NavigationService,
} from './navigation.js';
export {
  resolveDocumentLink,
  splitLinkDestination,
  type ResolvedLinkTarget,
} from './workspace-links.js';

// Revisions, sessions, workspace.
export {
  VaultRevisionService,
  checksumOf,
  type RevisionRecord,
  type RecordRevisionInput,
  type RevisionService,
  type VaultRevisionServiceOptions,
} from './revisions.js';
export {
  DocumentSessionImpl,
  type DocumentSession,
  type DocumentSessionDeps,
  type DocumentSessionState,
  type SaveResult,
} from './session.js';
export {
  WorkspaceServiceImpl,
  WorkspaceRebuildError,
  WORKSPACE_RECORD_PATH,
  type WorkspaceIdentityRecord,
  type WorkspaceTrashRecord,
  type CreateDocumentInput,
  type WorkspaceService,
  type WorkspaceServiceDeps,
} from './workspace.js';

// Service tokens.
export {
  vaultToken,
  documentRegistryToken,
  documentPresentationToken,
  metadataToken,
  relationshipsToken,
  commandsToken,
  settingsToken,
  navigationToken,
  revisionsToken,
  workspaceToken,
  searchToken,
  documentEditorRegistryToken,
  documentReaderRegistryToken,
  markdownEditorProviderToken,
  handwritingRecognizerToken,
  documentAssetStoreToken,
  blockRegistryToken,
  surfaceObjectRegistryToken,
  surfaceToolRegistryToken,
  compositionRegistryToken,
  compositionPresentationToken,
  keyboardInsetToken,
  stylusToken,
  purchasesToken,
  accountToken,
  vaultSyncToken,
  accountIdentityToken,
  externalFileDropToken,
  pdfProviderToken,
  pdfExportProviderToken,
  latexProviderToken,
  localVaultIdentityToken,
  ephemeralLocalVaultId,
  localVaultIdentity,
  type LocalVaultIdentity,
} from './tokens.js';

// PDF source/view/export contracts.
export {
  PDF_LIMITS,
  normalizePdfPageGeometry,
  sourcePointToSurface,
  pdfKind,
  pdfKindId,
  type PdfProvider,
  type PdfDocumentHandle,
  type PdfPageInfo,
  type PdfPageText,
  type PdfTextItem,
  type PdfOutlineEntry,
  type PdfLink,
  type PdfPageMountRequest,
  type PdfMountedPageHandle,
  type PdfExportProvider,
  type PdfExportRequest,
  type PdfExportWarning,
  type PdfExportWarningCode,
  type PdfSourceInteractionMode,
  type PdfSourceModel,
  type PdfBoxTuple,
  type PdfRotation,
  type PdfSourceGeometry,
  type PdfEffectiveBox,
  type NormalizedPdfPageGeometry,
} from './pdf/index.js';

// LaTeX document kind, structure, and render-provider contracts.
export {
  latexKind,
  latexKindId,
  isLaTeXPath,
  latexModel,
  latexStarterTemplate,
  extractLaTeXStructure,
  extractLaTeXMetadata,
  extractLaTeXRelationships,
  latexSearchText,
  latexSearchAnchors,
  latexSearchProjectionStart,
  decodeLaTeX,
  encodeLaTeX,
  latexFallbackTitleFromPath,
  LATEX_LIMITS,
  latexError,
  flattenLaTeX,
  applyLaTeXAssetUrls,
  latexJoinPath,
  latexRelativeJoinPath,
  latexDirOf,
  latexEnsureTexExtension,
  latexEnsureBibExtension,
  maskTeXComments,
  latexToPlainText,
  type LaTeXModel,
  type LaTeXStructure,
  type LaTeXSection,
  type LaTeXLabel,
  type LaTeXCitation,
  type LaTeXInclude,
  type LaTeXGraphic,
  type LaTeXBibliography,
  type LaTeXErrorCode,
  type LaTeXDiagnostic,
  type LaTeXSourceResolver,
  type LaTeXSourceMapping,
  type LaTeXRenderResult,
  type LaTeXDocumentHandle,
  type LaTeXProvider,
  type FlattenResult,
  type FlattenInput,
} from './latex/index.js';

// Portable encoding helpers used across capability seams.
export { utf8Decode, utf8Encode } from './encoding.js';

export {
  InMemoryCompositionRegistry,
  InMemoryCompositionPresentationRegistry,
  LazyCompositionController,
  MAX_COMPOSITION_DEPTH,
  compositionKey,
  type CompositionAction,
  type CompositionHandle,
  type CompositionImage,
  type CompositionItem,
  type CompositionPlaceholderReason,
  type CompositionProviderInput,
  type CompositionProviderRegistration,
  type CompositionRegistry,
  type CompositionPresenter,
  type CompositionPresentationHandle,
  type CompositionPresentationRegistry,
  type CompositionRequest,
  type CompositionRole,
  type CompositionSnapshot,
  type CompositionWriteAuthority,
  type ResourceResolver,
  type ResourceSuggestion,
} from './composition.js';

// Markdown document kind (host-agnostic, editor-free).
export {
  markdownKindId,
  markdownKind,
  markdownModel,
  decodeMarkdown,
  encodeMarkdown,
  fallbackTitleFromPath,
  parseFrontmatter,
  serializeFrontmatter,
  extractHeadings,
  extractBlocks,
  buildAddressIndex,
  slugify,
  extractLinks,
  extractTags,
  extractMarkdownMetadata,
  extractMarkdownRelationships,
  resolveMarkdownHrefToRef,
  searchMarkdownImageFiles,
  projectMarkdownForSearch,
  tokenize,
  type MarkdownModel,
  type FrontmatterResult,
  type HeadingInfo,
  type BlockInfo,
  type ExtractedLink,
  type LinkKind,
  type SearchDocument,
} from './markdown/index.js';

// Search (derived, rebuildable).
export {
  InMemorySearchService,
  type SearchService,
  type SearchQuery,
  type SearchResult,
} from './search/index.js';

// Block pages (host-agnostic, editor-free).
export {
  blockPageKindId,
  blockPageKind,
  BLOCK_PAGE_FORMAT_VERSION,
  BLOCK_PAGE_LIMITS,
  canonicalBlockPageJson,
  decodeBlockPage,
  encodeBlockPage,
  BLOCK_PAGE_BLOCK_TYPES,
  emptyBlockPage,
  paragraphBlock,
  headingBlock,
  codeBlock,
  imageBlock,
  listBlock,
  tableBlock,
  quoteBlock,
  dividerBlock,
  toggleBlock,
  calloutBlock,
  resourceLinkBlock,
  resourceEmbedBlock,
  transclusionBlock,
  linkedViewBlock,
  runsOf,
  inlineRunsOf,
  childrenOf,
  isCoreBlockType,
  isLinkMark,
  isResourceMark,
  isResourceTarget,
  isBareMark,
  isValidNamespacedTypeId,
  InMemoryBlockRegistry,
  extractBlockPageMetadata,
  extractBlockPageRelationships,
  projectBlockPageForSearch,
  importMarkdownToBlockPage,
  exportBlockPageToMarkdown,
  type DecodeBlockPageResult,
  type BlockPageWarning,
  type BlockPageWarningCode,
  type BlockId,
  type BlockPageModel,
  type BlockRecord,
  type BareMark,
  type CoreBlockType,
  type JsonAtom,
  type JsonRecord,
  type LinkMark,
  type ResourceMark,
  type ResourceTarget,
  type ListItem,
  type Mark,
  type Run,
  type BlockRegistry,
  type BlockTypeDescriptor,
  type SearchAnchor,
  type ConversionStatus,
  type ExportResult,
  type ImportResult,
  type ResourceMarkdownResolver,
} from './blocks/index.js';

// Editor capability seams.
export {
  InMemoryDocumentEditorRegistry,
  NO_SURFACE_TEXT_SELECTION,
  SURFACE_TEXT_COLOR_SWATCHES,
  SURFACE_TEXT_DEFAULT_COLOR,
  SURFACE_TEXT_DEFAULT_SIZE,
  SURFACE_TEXT_H1_MIN_SIZE,
  SURFACE_TEXT_H1_SIZE,
  SURFACE_TEXT_H2_MIN_SIZE,
  SURFACE_TEXT_H2_SIZE,
  SURFACE_TEXT_H3_SIZE,
  SURFACE_TEXT_ORDER,
  SURFACE_TEXT_SIZE_MAX,
  SURFACE_TEXT_SIZE_MIN,
  SURFACE_TEXT_SIZE_STEP,
  buildActiveToolSettingsControls,
  buildSurfaceArrangeControls,
  buildSurfaceDrawControls,
  buildSurfaceExportControl,
  buildSurfaceFitControl,
  buildSurfaceImageControl,
  buildSurfaceStyleControls,
  buildSurfaceTextControls,
  buildSurfaceZoomControls,
  activeSlotFamily,
  createSharedSurfaceDrawTools,
  createSharedSurfaceEraserTools,
  deriveSurfaceTextSelectionState,
  executeSurfaceTextControl,
  executeSurfaceToolbarControl,
  executeSurfaceToolSettingsControl,
  isExclusiveActiveToolControl,
  surfaceTextAlignControl,
  surfaceTextColorControl,
  surfaceTextControlIds,
  surfaceTextSizeControl,
  surfaceTextStyleControl,
  surfaceTextToggleControl,
  SURFACE_ERASER_MODES,
  SURFACE_HIGHLIGHTER_GLYPH_OPACITY,
  SURFACE_HIGHLIGHTER_SLOT_SWATCHES,
  SURFACE_HIGHLIGHTER_SLOT_WIDTHS,
  surfaceSlotSwatchesForFamily,
  surfaceSlotWidthsForFamily,
  SURFACE_PEN_SLOT_SWATCHES,
  SURFACE_PEN_SLOT_WIDTHS,
  WRITING_FORMAT_ORDER,
  WRITING_INSERT_ORDER,
  WRITING_STRUCTURE_ORDER,
  WRITING_STYLE_SEMANTIC_ROLE,
  writingCodeBlockControl,
  writingFormatToggleControl,
  writingIndentControl,
  writingLinkControl,
  writingOutdentControl,
  SURFACE_SHARED_ERASER_RANGE,
  SURFACE_SHARED_SWATCHES,
  SURFACE_SHARED_WIDTHS,
  SURFACE_TOOLBAR_ZOOM_STEP,
  type DocumentEditorHandle,
  type DocumentEditorProvider,
  type DocumentEditorRegistry,
  type DocumentEditorTools,
  type DocumentToolControl,
  type DocumentToolSnapshot,
  type SavedStyleCardData,
  type SavedStylePresetData,
  type SavedStylePressureData,
  type SavedStyleTipData,
  type SurfaceToolRole,
  type ToolbarActivationRole,
  type SharedSurfaceDrawDialect,
  type SharedSurfaceDrawKeys,
  type SharedSurfaceDrawSlot,
  type SharedSurfaceTextSlot,
  type SharedWritingFormatSlot,
  type SharedWritingInsertSlot,
  type SharedWritingStructureSlot,
  type SurfaceTextAlignValue,
  type SurfaceTextControlIds,
  type SurfaceTextExecuteHost,
  type SurfaceTextSelectionState,
  type SurfaceTextStyleValue,
  type SurfaceTextToggleState,
  type SurfaceToolbarArrangeOptions,
  type MarkdownEditorHandle,
  type MarkdownEditorProvider,
  type BlockPageEditorHandle,
  type BlockPageEditorProvider,
  type BlockPageEditorInput,
  type NotebookEditorHandle,
  type NotebookEditorProvider,
  type NotebookEditorInput,
  type DocumentSearchAnchor,
  type SurfaceToolbarDrawOptions,
  type SurfaceToolbarDrawTool,
  type SurfaceToolbarExecuteOptions,
  type SurfaceToolbarExportOptions,
  type SurfaceToolbarFitOptions,
  type SurfaceToolbarHost,
  type SurfaceToolbarImageOptions,
  type SurfaceToolbarStyleOptions,
  type SurfaceToolbarZoomOptions,
  type SurfaceToolSettingsHost,
  type SurfaceToolSettingsOptions,
  type WritingFormatPresentationOptions,
  type WritingLinkState,
  type WritingToggleState,
} from './editors/index.js';

// Reading-view capability seam (centralized edit/reading presentation).
export {
  InMemoryDocumentReaderRegistry,
  type DocumentReaderHandle,
  type DocumentReaderProvider,
  type DocumentReaderRegistry,
} from './reading/index.js';
export { sha256Hex } from './hashing.js';

// Surfaces (host-agnostic, renderer-free).
export {
  SURFACE_FORMAT_VERSION,
  SURFACE_LIMITS,
  SURFACE_OBJECT_TYPES,
  SURFACE_MAX_COORDINATE,
  SURFACE_MAX_STROKE_POINTS,
  SURFACE_MAX_TEXT_LENGTH,
  boundedFrame,
  canonicalSurfaceJson,
  cardObject,
  compileScene,
  createCamera,
  createDefaultSurfaceObjectTypeRegistry,
  createDefaultSurfaceToolRegistry,
  decodeSurfacePayload,
  dispatchScene,
  ellipseObject,
  emptySurface,
  encodeSurfacePayload,
  extendStrokeBounds,
  findGeometryLimitViolation,
  frameBounds,
  groupMembersOf,
  groupObject,
  groupOfMember,
  imageObject,
  infiniteFrame,
  inkStrokeObject,
  isCoreSurfaceObjectType,
  lineObject,
  isValidCoreSurfaceObject,
  itemAabb,
  logicalIdOf,
  normalizeBox,
  pointInEllipse,
  pointInPolygon,
  pointInRotatedBounds,
  pointPolylineDistance,
  renderSurfaceScene,
  resourceEmbedObject,
  rotatedBoundsAabb,
  rotateAround,
  rectangleObject,
  SurfaceInteractionController,
  InkToolController,
  IncrementalSceneCache,
  PROGRESSIVE_SAMPLES_PER_MS,
  FIRST_PAINT_MAX_COST,
  InMemorySurfaceToolRegistry,
  SURFACE_TOOL_IDS,
  HIGHLIGHTER_PRESET,
  DEFAULT_ERASER_RADIUS_VIEW,
  TEXT_ROLES,
  TEXT_ALIGNS,
  TEXT_DEFAULT_SIZE,
  TEXT_DEFAULT_WRAP_WIDTH,
  TEXT_LINE_HEIGHT_FACTOR,
  TEXT_AVG_ADVANCE_FACTOR,
  effectiveSurfaceTextSizeOf,
  effectiveTextSizeOf,
  estimateTextLineWidth,
  isKnownTextAlign,
  isKnownTextRole,
  isValidAppearanceSize,
  isValidWrapWidth,
  splitTextLines,
  textAlignOf,
  textBoldOf,
  textEstBounds,
  textItalicOf,
  textObject,
  textRoleOf,
  textV2EstBounds,
  textV2Lines,
  textWrapWidthOf,
  wrapTextLine,
  viewToSurface,
  viewportSurfaceRect,
  zoomCameraAt,
  InMemorySurfaceObjectTypeRegistry,
  SURFACE_MAX_SAMPLE_DT_MS,
  BALL_PEN_BRUSH,
  BRUSH_PEN_BRUSH,
  DEFAULT_ERASER_MODE,
  ERASER_FILTERS,
  ERASER_MODES,
  ERASER_MODE_BY_SEMANTIC_ROLE,
  ERASER_SEMANTIC_ROLE_BY_MODE,
  FOUNTAIN_PEN_BRUSH,
  GESTURE_THRESHOLDS,
  HIGHLIGHTER_BRUSH,
  INK_DEFAULT_WIDTH,
  INK_BRUSH_KINDS,
  INK_BRUSH_PRESETS,
  InkCurveBuilder,
  LASSO_MODES,
  PENCIL_BRUSH,
  TESSELLATION_DESIGN_ZOOM,
  TESSELLATION_TOLERANCE,
  arcLengthResample,
  buildStrokeMesh,
  compiledStrokeForRecord,
  compiledStrokeComputeStats,
  eraserSemanticRoleForPreset,
  isEraserMode,
  isUntranslated,
  normalizeEraserMode,
  preparedAabb,
  preparedItem,
  preparedItems,
  defaultControlSpacing,
  estimatePrepareCost,
  fairControlPolygon,
  fitCenterlineCurve,
  INK_COMPILER_VERSION,
  isCompiledWarm,
  MITER_LIMIT,
  smoothSamplesOfRecord,
  stabilizePositions,
  smoothSpineOfRecord,
  tessellateCurve,
  accumulateDerivedTranslation,
  derivedTranslationOfRecord,
  jointTranslationOfPacked,
  jointTranslationForChunk,
  resolveInkInteractionGeometry,
  materializeJointRichFromPacked,
  derivedTranslationStats,
  INK_TOOL_PREFERENCES_VERSION,
  InkPresetStore,
  inkSlotFamilyForTool,
  INK_PEN_FAMILY_TOOLS,
  LiveInkStrokeCompiler,
  brushPresetForKind,
  compileInkStroke,
  compileInkStrokeAsync,
  yieldToEventLoop,
  scheduleBackgroundCompile,
  asyncCompilerStats,
  ColdInkCompileScheduler,
  orderByPreparationPriority,
  serializeCompiledInk,
  rehydrateCompiledInk,
  PACKED_INK_TRANSPORT_VERSION,
  packCompiledInk,
  packInkSamples,
  packedCompiledByteLength,
  packedRenderCounters,
  resetPackedRenderCounters,
  packedRequestTransfer,
  packedResponseTransfer,
  packedSamplesTransfer,
  rebasePackedCompiledInk,
  unpackCompiledInk,
  unpackInkSamples,
  validatePackedCompiledInk,
  validatePackedSamples,
  liveCompilerCounters,
  liveCompilerStats,
  recognizeArrow,
  recognizeCircle,
  recognizeEllipse,
  recognizeLine,
  recognizeRectangle,
  recognizeScribble,
  recognizeShape,
  rebaseStrokeTiming,
  resetLiveCompilerStats,
  anchorPoint,
  reconcileConnectorEndpoints,
  resolveConnectorAnchor,
  routeConnector,
  invalidateCompiledForIds,
  invalidateCompiledForRecord,
  captureGeometryOwnershipForIds,
  recordGeometryGeneration,
  logicalGeometryGeneration,
  recordPositionGeneration,
  logicalPositionGeneration,
  rememberedLogicalIdOf,
  resolvePreparedBackgroundPackUnitForLogical,
  backgroundPackRendezvousKeysForIds,
  acknowledgeBackgroundPackRendezvousKeys,
  encodeBackgroundPackRendezvousKey,
  decodeBackgroundPackRendezvousKey,
  type BackgroundPackRendezvousKey,
  logicalMembersOf,
  resolvePreparedBackgroundPackUnit,
  resetGeometryGenerationsForTests,
  type PreparedBackgroundPackUnit,
  clearPackedCompiledForRecord,
  retainPackedForRecord,
  retainPackedOnlyForRecord,
  packedOnlyForRecord,
  hasPersistablePacked,
  packedCompiledForRecord,
  hasJointPacked,
  jointPackedForChunk,
  setCompiledForRecord,
  SurfaceSpatialIndex,
  ConnectorReverseIndex,
  SurfaceDerivedGeometryStore,
  SurfaceDerivedCache,
  DERIVED_CACHE_VERSION,
  DERIVED_CACHE_MAX_COMPILED,
  DERIVED_CACHE_MAX_COMPILED_BYTES,
  DERIVED_CACHE_DURABLE_MAX_BYTES,
  derivedCacheKey,
  derivedCacheEntryStorageKey,
  isDerivedCacheKeyCurrent,
  serializeDerivedCacheBinary,
  encodeDerivedCacheEntry,
  decodeDerivedCacheEntry,
  encodeDerivedCacheManifest,
  decodeDerivedCacheManifest,
  SURFACE_SEED_BOUNDS_KEY,
  SURFACE_SEED_BOUNDS_BY_PAGE_KEY,
  SURFACE_CANONICAL_CHECKSUM_KEY,
  isBoundsLike,
  isValidSeedBounds,
  checksumFromOpenMetadata,
  contentRevisionFromOpenMetadata,
  seedBoundsFromOpenMetadata,
  pageSeedBoundsFromOpenMetadata,
  DerivedReopenStore,
  collectPersistEntries,
  collectPersistEntriesAsync,
  createCachedCompiledRestore,
  createLiveCachedCompiledRestore,
  liveContentRevision,
  liveIsDirty,
  packDerivedCacheOnMain,
  packLazyManifestContainer,
  packLazyManifestOnMain,
  persistLiveReopenGeometry,
  persistWarmCompiledGeometry,
  persistWarmCompiledGeometryAsync,
  persistWarmCompiledRecordsAsync,
  scheduleBackgroundPackForPreparedUnit,
  scheduleBackgroundPackForRecords,
  setBackgroundPackWorkerFactory,
  flushBackgroundPackQueueForTests,
  resetBackgroundPackForTests,
  cancelBackgroundPackForTests,
  timeBackgroundInputInit,
  type BackgroundInputInitTiming,
  MAX_MAIN_THREAD_PACK_CHUNK_ITEMS,
  BACKGROUND_PACK_INPUT_SAMPLES_PER_SLICE,
  backgroundPackStats,
  persistenceTripwires,
  resolveReopenSeeds,
  restoreCachedCompiledGeometry,
  restoreLiveReopenGeometry,
  type CompiledRestoreSource,
  type BackgroundPackWorker,
  type DerivedCachePackEntry,
  type DerivedCachePackRequest,
  type DerivedCachePacker,
  type DerivedCacheLazyPackResult,
  type CachedCompiledRestoreStats,
  type SurfaceReopenBinding,
  cheapInkBounds,
  cheapSizedBounds,
  expandBounds,
  unionBounds,
  translateBounds,
  computeSnap,
  SNAP_GUIDE_COLOR,
  defaultRulerState,
  distanceToRuler,
  distanceToRulerSegment,
  isValidRulerState,
  normalizeRulerAngle,
  projectPointToRuler,
  rulerDirection,
  rulerEndpoints,
  rulerNormal,
  rulerSnapThresholdSurface,
  rulerToDrawItems,
  shouldSnapToRuler,
  snapSamplesToRuler,
  RULER_DEFAULT_LENGTH,
  RULER_GUIDE_COLOR,
  RULER_OVERLAY_ID,
  RULER_SNAP_THRESHOLD,
  RULER_SNAP_THRESHOLD_VIEW,
  resolveBrushSpec,
  resolveBrushFootprint,
  NEUTRAL_PRESSURE,
  resolveGroupMembers,
  resolveStrokeBrush,
  sizedConnectorAnchor,
  type AlignEdge,
  type BoundedFrame,
  type Bounds,
  type Camera,
  type SurfaceControllerStats,
  type SurfaceSpatialIndexStats,
  type ConnectorIndexStats,
  type DerivedStoreStats,
  type SelectionDragSession,
  type CardGeometry,
  type DecodeSurfacePayloadResult,
  type DistributeAxis,
  type DrawItem,
  type CardItem,
  type GroupGeometry,
  type ResourceEmbedItem,
  type EraserStyleRef,
  type ArrowFit,
  type CircleHit,
  type CompiledInkStroke,
  type ConnectorAnchor,
  type ConnectorEndpointBinding,
  type ConnectorPath,
  type EllipseFit,
  type EraserFilter,
  type EraserMode,
  type EraserPreset,
  type GesturePreferences,
  type InkBrushKind,
  type InkBrushOverrides,
  type InkBrushSpec,
  type InkBrushFootprint,
  type InkBrushTip,
  type InkBrushDescriptor,
  type InkCurve,
  type InkCurveControl,
  type InkCurveSegment,
  type InkGeometryOptions,
  type InkInputBatch,
  type InkInterpolatedAttributes,
  type InkPresetStoreOptions,
  type InkPresetToolId,
  type InkSlotFamily,
  type InkPressureResponse,
  type InkSample,
  type InkYieldFn,
  type IncrementalSceneStats,
  type ColdCompileJobInput,
  type ColdCompileResult,
  type ColdCompileWorker,
  type ColdSchedulerOptions,
  type ColdSchedulerStats,
  type InkCompileRequest,
  type InkCompileResponse,
  type InkCompiledResponse,
  type InkCompileErrorResponse,
  type SerializableCompiledInk,
  type SerializedInkNode,
  type PackedCompiledInk,
  type PackedInkCompileRequest,
  type PackedInkCompileResponse,
  type PackedInkCompiledResponse,
  type PackedInkCompileErrorResponse,
  type PackedInkSamples,
  type DerivedCacheKey,
  type CachedCompiledGeometry,
  type CachedDerivedBounds,
  type DerivedCacheSerializedEntry,
  type SurfaceDerivedCacheOptions,
  type SurfaceDerivedCacheStats,
  type SurfaceOpenMetadata,
  type DerivedCacheStoragePort,
  type PersistCompiledStats,
  type ReopenSeedStats,
  type ResolveReopenSeedsInput,
  type ResolveReopenSeedsResult,
  type RestoreCompiledInput,
  type RestoreCompiledStats,
  type InkStrokeGeometry,
  type InkStrokeMesh,
  type InkStrokeNode,
  type TessellatedSpinePoint,
  type InkTilt,
  type LineArrows,
  type LineFit,
  type LineGeometry,
  type RectFit,
  type InkToolControllerOptions,
  type InkToolPreferencesV1,
  type InkToolPreset,
  type LineArrowSetting,
  type LassoMode,
  type LassoPreset,
  type LiveCompilerStats,
  type LiveInkGeometryUpdate,
  type LiveInkPreviewUpdate,
  type LiveStrokeMeshView,
  type PredictedTailUpdate,
  type SurfaceToolPresetState,
  SurfaceStyleLibrary,
  SURFACE_STYLE_LIBRARY_VERSION,
  type SurfaceStyleLibraryState,
  type SurfaceStylePreset,
  type NormalizedPointerEvent,
  type PenGestureOptions,
  type PenStyleRef,
  type Point,
  type PolylineItem,
  type PreparedItem,
  type DispatchSceneInput,
  type PreparedScene,
  type PreparedTransform,
  type PackedStrokeItem,
  type RenderViewport,
  type ResourceEmbedGeometry,
  type Size,
  type StrokeBounds,
  type StrokeItem,
  type LineItem,
  type SurfaceFrame,
  type SurfaceModel,
  type SurfaceObjectId,
  type SurfaceObjectRecord,
  type SurfaceObjectTypeDescriptor,
  type SurfaceObjectTypeRegistry,
  type SurfaceRendererBackend,
  type ReorderDirection,
  type ScribbleHit,
  type SelectionContentKind,
  selectionHandles,
  type SelectionContextSnapshot,
  type SelectionStyle,
  type ShapeFit,
  type SnapGuide,
  type SnapResult,
  type SurfaceRulerState,
  type SurfaceTool,
  type SurfaceToolContext,
  type SurfaceToolRegistry,
  type SurfaceWarning,
  type SurfaceWarningCode,
  type TextAlign,
  type TextAppearance,
  type TextItem,
  type TextRole,
  inkPageKindId,
  inkPageKind,
  inkStrokeCompiledBounds,
  inkStrokeEnvelope,
  localAnchorPoint,
  materializeLiveMeshRing,
  maxStrokeHalfWidth,
  type InkInteractionGeometry,
} from './surfaces/index.js';

// Whiteboards (infinite surface document).
export {
  whiteboardKind,
  whiteboardKindId,
  WHITEBOARD_FORMAT_VERSION,
  WHITEBOARD_LIMITS,
  decodeWhiteboard,
  encodeWhiteboard,
  canonicalWhiteboardJson,
  extractWhiteboardMetadata,
  extractWhiteboardRelationships,
  projectWhiteboardForSearch,
  type WhiteboardModel,
  type WhiteboardObjectRecord,
  type WhiteboardObjectId,
  type WhiteboardFrame,
  type DecodeWhiteboardResult,
  type WhiteboardWarning,
  WHITEBOARD_OBJECT_TYPES,
} from './whiteboard/index.js';

// Notebooks.
export {
  appendPage,
  emptyNotebook,
  baseOf,
  isNavigablePage,
  labelOf,
  navigablePageIds,
  notebookKind,
  notebookKindId,
  notebookPage,
  pdfNotebookPage,
  NOTEBOOK_DEFAULT_PAGE_HEIGHT,
  NOTEBOOK_DEFAULT_PAGE_WIDTH,
  NOTEBOOK_FORMAT_VERSION,
  setPageLabel,
  setPageTemplate,
  templateOf,
  paperOptionsOf,
  setPaperOptions,
  decodeNotebook,
  encodeNotebook,
  canonicalNotebookJson,
  projectNotebookForSearch,
  NOTEBOOK_LIMITS,
  type DecodeNotebookResult,
  type NotebookModel,
  type NotebookPage,
  type NotebookPageEntry,
  type NotebookPageId,
  type NotebookPageOptions,
  type PdfNotebookPageOptions,
  type NotebookPageBase,
  type TemplateNotebookPageBase,
  type PdfNotebookPageBase,
  type NotebookPageBox,
  type OpaqueNotebookPage,
} from './notebooks/index.js';
export {
  DEFAULT_NOTEBOOK_TEMPLATE,
  defaultPaperSpacingForTemplate,
  isCoreNotebookTemplate,
  templateBackgroundDrawItems,
  NOTEBOOK_TEMPLATES,
  type CoreNotebookTemplate,
} from './notebooks/templates.js';
export {
  isValidPaperOptions,
  normalizePaperOptions,
  resolvePaperColor,
  resolvePaperSpacing,
  pageSizePreset,
  orientSize,
  orientationOf,
  PAPER_SPACING_MIN,
  PAPER_SPACING_MAX,
  PAPER_COLOR_MAX_LENGTH,
  NOTEBOOK_PAGE_SIZES,
  NOTEBOOK_PAGE_SIZE_IDS,
  type NotebookPaperOptions,
  type NotebookPageSizeId,
  type NotebookPageOrientation,
  type NotebookPageDimensions,
} from './notebooks/paper.js';
export {
  HandwritingAwareSearchService,
  notebookHandwritingQueries,
  type HandwritingQueryPage,
  type HandwritingRecognizer,
  type RecognizedHandwritingLine,
} from './notebooks/recognition.js';

// Plugins.
export {
  memoryVaultPlugin,
  type MemoryVaultPluginConfig,
} from './plugins/memory-vault.js';
export {
  workspacePlugin,
  type WorkspacePluginConfig,
} from './plugins/workspace.js';

// Overlay keyboard-inset capability.
export {
  KEYBOARD_INSET_EVENT_CHANNEL,
  KEYBOARD_INSET_FALLBACK_HEIGHT,
  KEYBOARD_INSET_STORAGE_KEY,
  computeKeyboardBottomInset,
  noopKeyboardInsetTransport,
  readKeyboardInsetMeasurement,
  reconcileKeyboardInsetTarget,
  type KeyboardInsetListener,
  type KeyboardInsetMeasurement,
  type KeyboardInsetNativeEventName,
  type KeyboardInsetRect,
  type KeyboardInsetService,
  type KeyboardInsetSettledListener,
  type KeyboardInsetSnapshot,
  type KeyboardInsetTargetEvent,
  type KeyboardInsetTargetListener,
  type KeyboardInsetTransport,
  type KeyboardInsetWillHideEvent,
  type KeyboardInsetWillHideListener,
} from './keyboard-inset/contract.js';
export {
  KeyboardInsetStore,
  type KeyboardInsetStorage,
  type KeyboardInsetStoreOptions,
  type KeyboardInsetTimer,
} from './keyboard-inset/store.js';
export {
  createKeyboardInset,
  type KeyboardInsetHost,
  type KeyboardInsetHostOptions,
} from './keyboard-inset/plugin.js';

// Stylus accessory capability: semantic events only, never samples.
export {
  DEFAULT_STYLUS_CAPABILITIES,
  DEFAULT_STYLUS_DEVICE_CAPABILITIES,
  STYLUS_NATIVE_EVENT_CHANNEL,
  observedPenFlags,
  type NativeStylusCapabilities,
  type StylusAction,
  type StylusActionListener,
  type StylusCapabilities,
  type StylusCapabilitiesListener,
  type StylusDeviceCapabilities,
  type StylusDeviceCapabilitiesListener,
  type StylusHostCapabilities,
  type StylusNativeEventName,
  type StylusObservedPenFlags,
  type StylusObservedPenSample,
  type StylusPreferredAction,
  type StylusService,
  type StylusInputContext,
  type StylusInputPolicy,
  type StylusSqueezePhase,
  type StylusViewportAnchor,
} from './stylus/contract.js';
export { InMemoryStylusService } from './stylus/service.js';
export {
  createStylusHost,
  type StylusHost,
  type StylusHostOptions,
} from './stylus/plugin.js';
// Account identity capability: Firebase UID as the stable
// opaque account identity; email is credential-only.
export {
  AccountError,
  AccountStore,
  createAccountHost,
  hasServerEntitlement,
  isAccountError,
  isAccountErrorCode,
  normalizeAccountError,
  unconfiguredAccountTransport,
  type AccountErrorCode,
  type AccountHost,
  type AccountHostOptions,
  type AccountId,
  type AccountService,
  type AccountSnapshot,
  type AccountSnapshotListener,
  type AccountStoreOptions,
  type AccountTokenState,
  type AccountTransport,
  type AccountUser,
} from './account/index.js';
// Account ↔ purchase identity binding: Firebase UID becomes
// the RevenueCat App User ID; ordered sign-out dismantles cloud authority.
export {
  AccountIdentityCoordinator,
  createAccountIdentityHost,
  type AccountIdentityBinding,
  type AccountIdentityCoordinatorOptions,
  type AccountIdentityHost,
  type AccountIdentityHostOptions,
  type AccountIdentityService,
  type AccountIdentitySnapshot,
  type AccountIdentitySnapshotListener,
} from './account-identity/index.js';
// Vault sync protocol: Froglight-owned manifests,
// three-way merge, and the provider-neutral remote contract. Firebase
// Firebase implements `SyncRemote`; the memory remote serves tests.
export {
  ManualDirtyTracker,
  MemorySyncRemote,
  ObservableVaultService,
  SYNC_LIMITS,
  SYNC_MANIFEST_FORMAT,
  SYNC_PROTOCOL_VERSION,
  SyncScheduler,
  VaultSyncError,
  VaultSyncStore,
  WorkspaceDirtyTracker,
  WorkspaceSyncReconciler,
  asObservableVault,
  assignConflictDirectory,
  assignConflictPath,
  blobHex,
  blobRef,
  buildManifest,
  canonicalizeManifest,
  createMemorySyncStorage,
  createVaultSyncAttachment,
  createVaultSyncHost,
  emptyManifest,
  generateCloudVaultId,
  generateDeviceId,
  hashBytes,
  hashManifest,
  isBlobRef,
  isDefaultExcludedSyncPath,
  isManifestHash,
  isRemoteChanged,
  isVaultSyncError,
  isVaultSyncErrorCode,
  manifestsEqual,
  normalizeSyncError,
  parseManifestBytes,
  parseRemoteHead,
  parseStoredSyncState,
  parseSyncManifest,
  createLocalScanCache,
  reconcileVault,
  sortManifestEntries,
  threeWayMerge,
  verifyBlob,
  withObservableVault,
  type BlobRef,
  type IncrementalScanOptions,
  type LocalScanCache,
  type LocalScanCacheEntry,
  type ExpectedHead,
  type ManifestHash,
  type MergeOptions,
  type MergePlan,
  type ReconcileInput,
  type ReconcileResult,
  type RemoteHead,
  type RemoteHeadInput,
  type PreparedRemoteVault,
  type RemoteVaultInfo,
  type StoredSyncState,
  type SyncBase,
  type SyncBinding,
  type SyncConflict,
  type SyncConflictKind,
  type SyncDirtyTracker,
  type SyncManifest,
  type SyncManifestEntry,
  type SyncProgressStage,
  type SyncRemote,
  type SyncSchedulerOptions,
  type SyncSchedulerTimer,
  type AccountSyncState,
  type SyncAppliedNotification,
  type SyncWorkspaceReconciler,
  type VaultSyncBinding,
  type VaultSyncBindingView,
  type VaultSyncConflictRecovery,
  type VaultSyncConflictSummary,
  type VaultSyncEnableInput,
  type VaultMutation,
  type VaultMutationListener,
  type VaultSyncErrorCode,
  type VaultSyncHost,
  type VaultSyncHostOptions,
  type VaultSyncPhase,
  type VaultSyncService,
  type VaultSyncEntitlementOptions,
  type VaultSyncServiceOptions,
  type VaultSyncSnapshot,
  type VaultSyncSnapshotListener,
  type VaultSyncStorage,
  type WorkspaceDirtyTrackerOptions,
  type WorkspaceSyncReconcilerOptions,
} from './sync/index.js';
// External file ingress (`froglight.file-drop`): opaque native handles,
// lazy reads, browser HTML5 path primary. Trusted-tier only.
export {
  FILE_DROP_NATIVE_EVENT_CHANNEL,
  type ExternalDropEvent,
  type ExternalDropFile,
  type ExternalDropListener,
  type ExternalDropPosition,
  type ExternalFileDropResolver,
  type ExternalFileDropService,
  type FileDropNativeEventName,
  type NativeFileDropFilePayload,
  type NativeFileDropPositionPayload,
} from './file-drop/contract.js';
export {
  InMemoryExternalFileDropService,
  type InMemoryFileDropOptions,
} from './file-drop/service.js';
export {
  createFileDropHost,
  type FileDropHost,
  type FileDropHostOptions,
} from './file-drop/plugin.js';
export type { StoredAsset, DocumentAssetStore } from './assets.js';
export * from './databases/index.js';
export * from './resource-properties/index.js';
export {
  VAULT_PROFILE_PATH,
  VAULT_ICONS,
  VAULT_COLORS,
  DEFAULT_VAULT_APPEARANCE,
  decodeVaultProfile,
  readVaultProfile,
  writeVaultProfile,
  type VaultAppearance,
  type VaultProfile,
  type VaultIcon,
  type VaultColor,
} from './vault/profile.js';

export * from './surface-persistence.js';

export { observeSurfaceTransactions, publishSurfaceObjects, applySurfaceOrderEdits, type SurfaceOrderEdit } from './surfaces/transactions.js';

export { prepareInkRegion, regionOfContours } from './surfaces/ink/erasure.js';
export {
  cloneInkRecord,
  freezeInkValue,
  INK_SOURCE_TYPE,
} from './surfaces/ink/fragments.js';
export type {
  ErasurePreparation,
  ErasureRefinement,
} from './surfaces/ink/erasure-preparation.js';

export type { InkErasure } from './surfaces/ink/erasure.js';

export { drainSurfaceDocumentWork } from './surfaces/transactions.js';

export {
  packInkRegion,
  bindInkSource,
  inkRegion,
  validInkVisible,
} from './surfaces/ink/fragments.js';
export { inkSourceOutline } from './surfaces/ink/source-geometry.js';
export type {
  PreparedInkRegion,
  InkRegionTransform,
  InkVisibleRegion,
} from './surfaces/ink/fragments.js';

export { SurfaceDurabilityValidator } from './surfaces/durability-validation.js';

export { releaseInkSourceGeometry } from './surfaces/ink/source-geometry.js';

export { retrySurfaceDocumentWork } from './surfaces/transactions.js';

export { isSurfaceRefinementOrderEdit } from './surfaces/transactions.js';

export { inkSourceRetainedBytes } from './surfaces/ink/fragments.js';
