export {
  SURFACE_OBJECT_TYPES,
  SURFACE_MAX_COORDINATE,
  SURFACE_MAX_SAMPLE_DT_MS,
  SURFACE_MAX_STROKE_POINTS,
  SURFACE_MAX_TEXT_LENGTH,
  TEXT_ROLES,
  TEXT_ALIGNS,
  TEXT_DEFAULT_SIZE,
  TEXT_DEFAULT_WRAP_WIDTH,
  TEXT_LINE_HEIGHT_FACTOR,
  TEXT_AVG_ADVANCE_FACTOR,
  boundedFrame,
  cardObject,
  effectiveSurfaceTextSizeOf,
  effectiveTextSizeOf,
  ellipseObject,
  emptySurface,
  findGeometryLimitViolation,
  frameBounds,
  groupObject,
  imageObject,
  infiniteFrame,
  inkStrokeObject,
  isCoreSurfaceObjectType,
  isKnownTextAlign,
  isKnownTextRole,
  isValidAppearanceSize,
  isValidCoreSurfaceObject,
  isValidNamespacedTypeId,
  isValidWrapWidth,
  lineObject,
  rebaseLogicalChunkTiming,
  rebaseStrokeTiming,
  rectangleObject,
  resourceEmbedObject,
  textAlignOf,
  textBoldOf,
  textItalicOf,
  textObject,
  textRoleOf,
  textWrapWidthOf,
  chunkIndexOf,
  isLogicalChunk,
  logicalIdOf,
  type BoundedFrame,
  type CardGeometry,
  type CoreSurfaceObjectType,
  type GroupGeometry,
  type ImageGeometry,
  type InfiniteFrame,
  type ConnectorAnchor,
  type ConnectorEndpointBinding,
  type ConnectorPath,
  type InkSample,
  type InkTilt,
  type InkBrushDescriptor,
  type InkStrokeGeometry,
  type LineArrows,
  type LineGeometry,
  type JsonAtom,
  type JsonRecord,
  type JsonValue,
  type RectangleGeometry,
  type ResourceEmbedGeometry,
  type SurfaceFrame,
  type SurfaceModel,
  type SurfaceObjectId,
  type SurfaceObjectRecord,
  type TextAlign,
  type TextAppearance,
  type TextGeometry,
  type TextRole,
} from './model.js';
export {
  SURFACE_FORMAT_VERSION,
  SURFACE_LIMITS,
  canonicalSurfaceJson,
  decodeSurfacePayload,
  encodeSurfacePayload,
  type DecodeSurfacePayloadResult,
  type SurfaceWarning,
  type SurfaceWarningCode,
} from './codec.js';
export {
  boundsIntersect,
  centerOfBounds,
  createCamera,
  estimateTextLineWidth,
  finiteNumber,
  normalizeBox,
  pointInEllipse,
  pointInPolygon,
  pointInRotatedBounds,
  pointPolylineDistance,
  pointSegmentDistance,
  rotatedBoundsAabb,
  rotateAround,
  segmentIntersectsCapsule,
  segmentIntersectsDisc,
  segmentIntersectsPolygon,
  segmentSegmentDistance,
  segmentsIntersect,
  splitTextLines,
  surfaceToView,
  textEstBounds,
  textV2EstBounds,
  textV2Lines,
  unrotateAround,
  viewToSurface,
  viewportSurfaceRect,
  wrapTextLine,
  zoomCameraAt,
  type Bounds,
  type Camera,
  type Point,
  type Size,
} from './geometry.js';
export {
  INK_DEFAULT_WIDTH,
  INK_HIT_TOLERANCE,
  INK_COMPILER_VERSION,
  accumulateDerivedTranslation,
  clearJointPackedForChunks,
  compiledStrokeComputeStats,
  compiledStrokeForRecord,
  materializeRichFromPacked,
  materializeJointRichFromPacked,
  resolveInkInteractionGeometry,
  jointTranslationOfPacked,
  jointTranslationForChunk,
  packedOutlineOfRecord,
  hasJointPacked,
  hasRichCompiledGeometry,
  jointPackedForChunk,
  peekCompiledForRecord,
  retainJointPackedForChunks,
  derivedTranslationOfRecord,
  derivedTranslationStats,
  estimatePrepareCost,
  clearPackedCompiledForRecord,
  retainPackedForRecord,
  retainPackedOnlyForRecord,
  packedOnlyForRecord,
  hasPersistablePacked,
  invalidateCompiledForIds,
  invalidateCompiledForRecord,
  captureGeometryOwnershipForIds,
  recordGeometryGeneration,
  logicalGeometryGeneration,
  recordPositionGeneration,
  logicalPositionGeneration,
  rememberedLogicalIdOf,
  resolvePreparedBackgroundPackUnitForLogical,
  backgroundPackRendezvousKeysForIds,
  acknowledgeBackgroundPackRendezvousKeys,
  encodeBackgroundPackRendezvousKey,
  decodeBackgroundPackRendezvousKey,
  type BackgroundPackRendezvousKey,
  logicalMembersOf,
  resolvePreparedBackgroundPackUnit,
  resetGeometryGenerationsForTests,
  type PreparedBackgroundPackUnit,
  isCompiledWarm,
  packedCompiledForRecord,
  setCompiledForRecord,
  groupMembersOf,
  groupOfMember,
  inkSamplesOf,
  inkStrokeCompiledBounds,
  inkStrokeEnvelope,
  inkTypedSamplesOf,
  localAnchorPoint,
  looseEnvelopeBounds,
  maxStrokeHalfWidth,
  placeholderFor,
  resolveGroupMembers,
  resolveStrokeBrush,
  rotationOf,
  sizedConnectorAnchor,
  smoothSamplesOfRecord,
  smoothSpineOfRecord,
} from './objects.js';
export {
  DEFAULT_ERASER_MODE,
  ERASER_FILTERS,
  ERASER_MODES,
  LASSO_MODES,
  isEraserMode,
  matchesEraserFilter,
  segmentIntersectsBox,
  type EraserFilter,
  type EraserMode,
  type LassoMode,
} from './ink/eraser-geometry.js';
export {
  anchorPoint,
  reconcileConnectorEndpoints,
  resolveConnectorAnchor,
  routeConnector,
} from './ink/connectors.js';
export {
  computeSnap,
  SNAP_GUIDE_COLOR,
  type SnapGuide,
  type SnapResult,
} from './snap.js';
export {
  defaultRulerState,
  distanceToRuler,
  distanceToRulerSegment,
  isValidRulerState,
  normalizeRulerAngle,
  projectPointToRuler,
  rulerDirection,
  rulerEndpoints,
  rulerNormal,
  rulerSnapThresholdSurface,
  rulerToDrawItems,
  shouldSnapToRuler,
  snapSamplesToRuler,
  RULER_DEFAULT_LENGTH,
  RULER_GUIDE_COLOR,
  RULER_OVERLAY_ID,
  RULER_SNAP_THRESHOLD,
  RULER_SNAP_THRESHOLD_VIEW,
  type SurfaceRulerState,
} from './ruler.js';
export {
  InMemorySurfaceObjectTypeRegistry,
  type SurfaceObjectTypeDescriptor,
  type SurfaceObjectTypeRegistry,
} from './registry.js';
export { createDefaultSurfaceObjectTypeRegistry } from './objects.js';
export {
  isUntranslated,
  materializeLiveMeshRing,
  preparedItem,
  preparedItems,
} from './draw.js';
export type {
  CardItem,
  DrawItem,
  EllipseItem,
  ImageRefItem,
  LineItem,
  LiveStrokeMeshView,
  PackedStrokeItem,
  PlaceholderItem,
  PolylineItem,
  PreparedItem,
  PreparedTransform,
  RectItem,
  ResourceEmbedItem,
  StrokeItem,
  TextItem,
} from './draw.js';
export type { RenderViewport, SurfaceRendererBackend } from './backend.js';
export {
  compileScene,
  dispatchScene,
  itemAabb,
  preparedAabb,
  renderSurfaceScene,
  type DispatchSceneInput,
  type PreparedScene,
} from './render.js';
export {
  IncrementalSceneCache,
  PROGRESSIVE_SAMPLES_PER_MS,
  FIRST_PAINT_MAX_COST,
  orderByPreparationPriority,
  type CompiledRestoreSource,
  type IncrementalSceneStats,
} from './incremental-scene.js';
export {
  expandLogicalIds,
  groupLogicalChunks,
  logicalHead,
  logicalSamples,
  type LogicalStrokeGroup,
} from './logical-stroke.js';
export type { InkInteractionGeometry } from './objects.js';
export {
  SurfaceInteractionController,
  type AlignEdge,
  type DistributeAxis,
  type InkInputBatch,
  type NormalizedPointerEvent,
  type NormalizedWheelEvent,
  type SurfaceControllerStats,
  type SurfaceInteractionControllerOptions,
} from './controller.js';
export {
  SurfaceSpatialIndex,
  expandBounds,
  unionBounds,
  type SurfaceSpatialIndexStats,
} from './spatial-index.js';
export {
  ConnectorReverseIndex,
  type ConnectorIndexStats,
} from './connector-index.js';
export {
  SurfaceDerivedGeometryStore,
  cheapInkBounds,
  cheapSizedBounds,
  type DerivedStoreStats,
} from './derived-store.js';
export {
  SurfaceDerivedCache,
  DERIVED_CACHE_VERSION,
  DERIVED_CACHE_MAX_COMPILED,
  DERIVED_CACHE_MAX_COMPILED_BYTES,
  DERIVED_CACHE_DURABLE_MAX_BYTES,
  derivedCacheKey,
  derivedCacheEntryStorageKey,
  isDerivedCacheKeyCurrent,
  serializeDerivedCacheBinary,
  encodeDerivedCacheEntry,
  decodeDerivedCacheEntry,
  encodeDerivedCacheManifest,
  decodeDerivedCacheManifest,
  type CachedCompiledGeometry,
  type DerivedCacheKey,
  type DerivedCacheSerializedEntry,
  type CachedDerivedBounds,
  type DerivedCacheManifest,
  type DerivedCacheManifestEntry,
  type SurfaceDerivedCacheOptions,
  type SurfaceDerivedCacheStats,
} from './derived-cache.js';
export {
  SURFACE_SEED_BOUNDS_KEY,
  SURFACE_SEED_BOUNDS_BY_PAGE_KEY,
  SURFACE_CANONICAL_CHECKSUM_KEY,
  isBoundsLike,
  isValidSeedBounds,
  checksumFromOpenMetadata,
  contentRevisionFromOpenMetadata,
  seedBoundsFromOpenMetadata,
  pageSeedBoundsFromOpenMetadata,
  type SurfaceOpenMetadata,
} from './open-metadata.js';
export {
  DerivedReopenStore,
  MAX_MAIN_THREAD_PACK_CHUNK_ITEMS,
  BACKGROUND_PACK_INPUT_SAMPLES_PER_SLICE,
  backgroundPackDiagnostics,
  cancelBackgroundPackForTests,
  collectPersistEntries,
  collectPersistEntriesAsync,
  createCachedCompiledRestore,
  createLiveCachedCompiledRestore,
  flushBackgroundPackQueueForTests,
  liveContentRevision,
  liveIsDirty,
  packDerivedCacheOnMain,
  packLazyManifestContainer,
  packLazyManifestOnMain,
  persistLiveReopenGeometry,
  persistWarmCompiledGeometry,
  persistWarmCompiledGeometryAsync,
  persistWarmCompiledRecordsAsync,
  resetBackgroundPackForTests,
  scheduleBackgroundPackForPreparedUnit,
  scheduleBackgroundPackForRecords,
  setBackgroundPackWorkerFactory,
  backgroundPackStats,
  timeBackgroundInputInit,
  type BackgroundInputInitTiming,
  persistenceTripwires,
  resolveReopenSeeds,
  restoreCachedCompiledGeometry,
  restoreLiveReopenGeometry,
  type BackgroundPackWorker,
  type CachedCompiledRestoreStats,
  type DerivedCachePackEntry,
  type DerivedCachePackRequest,
  type DerivedCachePacker,
  type DerivedCacheLazyPackResult,
  type DerivedCacheStoragePort,
  type PersistCompiledAsyncOptions,
  type PersistCompiledStats,
  type ReopenSeedStats,
  type ResolveReopenSeedsInput,
  type ResolveReopenSeedsResult,
  type RestoreCompiledInput,
  type RestoreCompiledStats,
  type SurfaceReopenBinding,
} from './derived-reopen.js';
export {
  type SelectionDragSession,
  translateBounds,
} from './selection-drag.js';
export {
  createDefaultSurfaceToolRegistry,
  DEFAULT_ERASER_RADIUS_VIEW,
  extendStrokeBounds,
  HIGHLIGHTER_PRESET,
  InMemorySurfaceToolRegistry,
  InkToolController,
  SURFACE_TOOL_IDS,
  type EraserStyleRef,
  type InkToolControllerOptions,
  type PenGestureOptions,
  type PenStyleRef,
  type ReorderDirection,
  type SelectionContentKind,
  type SelectionContextSnapshot,
  type SelectionStyle,
  type StrokeBounds,
  type SurfaceTool,
  type SurfaceToolContext,
  type SurfaceToolRegistry,
} from './tools.js';
export {
  BALL_PEN_BRUSH,
  BRUSH_PEN_BRUSH,
  FOUNTAIN_PEN_BRUSH,
  HIGHLIGHTER_BRUSH,
  INK_BRUSH_KINDS,
  INK_BRUSH_PRESETS,
  PENCIL_BRUSH,
  brushPresetForKind,
  resolveBrushSpec,
  type InkBrushKind,
  type InkBrushOverrides,
  type InkBrushSpec,
  type InkBrushTip,
  type InkPressureResponse,
} from './ink/brush.js';
export {
  compileInkStroke,
  type CompiledInkStroke,
  type InkCurve,
  type InkCurveControl,
  type InkCurveSegment,
  type InkGeometryOptions,
  type InkInterpolatedAttributes,
  type InkStrokeMesh,
  type InkStrokeNode,
  type TessellatedSpinePoint,
} from './ink/geometry.js';
export {
  NEUTRAL_PRESSURE,
  resolveBrushFootprint,
  type InkBrushFootprint,
} from './ink/curve-attributes.js';
export {
  compileInkStrokeAsync,
  yieldToEventLoop,
  scheduleBackgroundCompile,
  asyncCompilerStats,
  type InkYieldFn,
} from './ink/async-compiler.js';
export {
  ColdInkCompileScheduler,
  type ColdCompileJobInput,
  type ColdCompileResult,
  type ColdCompileWorker,
  type ColdSchedulerOptions,
  type ColdSchedulerStats,
} from './ink/cold-scheduler.js';
export {
  serializeCompiledInk,
  rehydrateCompiledInk,
  type InkCompileRequest,
  type InkCompileResponse,
  type InkCompiledResponse,
  type InkCompileErrorResponse,
  type SerializableCompiledInk,
  type SerializedInkNode,
} from './ink/compile-protocol.js';
export {
  NODE_HAS_CORNER,
  PACKED_INK_TRANSPORT_VERSION,
  PRES_HAS_DT,
  PRES_HAS_PRESSURE,
  PRES_HAS_TILT,
  PRES_HAS_TWIST,
  packCompiledInk,
  packInkSamples,
  packedCompiledByteLength,
  packedRenderCounters,
  resetPackedRenderCounters,
  packedNodeEquals,
  packedRequestTransfer,
  packedResponseTransfer,
  packedSamplesTransfer,
  rebasePackedCompiledInk,
  unpackCompiledInk,
  unpackInkSamples,
  validatePackedCompiledInk,
  validatePackedSamples,
  type PackedCompiledInk,
  type PackedCompiledResult,
  type PackedInkCompileErrorResponse,
  type PackedInkCompileRequest,
  type PackedInkCompileResponse,
  type PackedInkCompiledResponse,
  type PackedInkSamples,
  type PackedSamplesResult,
} from './ink/packed-protocol.js';
export { arcLengthResample, defaultControlSpacing } from './ink/resample.js';
export { fairControlPolygon, stabilizePositions } from './ink/stabilization.js';
export { fitCenterlineCurve, InkCurveBuilder } from './ink/curve.js';
export {
  TESSELLATION_DESIGN_ZOOM,
  TESSELLATION_TOLERANCE,
  tessellateCurve,
} from './ink/tessellation.js';
export { buildStrokeMesh, MITER_LIMIT } from './ink/outline.js';
export {
  LIVE_PREDICT_SNAPSHOT_TAIL,
  LIVE_PREDICT_MAX_SAMPLES,
  LIVE_COMPILER_TAIL_WINDOW,
  LiveInkStrokeCompiler,
  liveCompilerCounters,
  liveCompilerStats,
  resetLiveCompilerStats,
  type LiveCompilerStats,
  type LiveInkGeometryUpdate,
  type LiveInkPreviewUpdate,
  type PredictedTailUpdate,
} from './ink/live-compiler.js';
export {
  ERASER_MODE_BY_SEMANTIC_ROLE,
  ERASER_SEMANTIC_ROLE_BY_MODE,
  INK_TOOL_PREFERENCES_VERSION,
  InkPresetStore,
  eraserSemanticRoleForPreset,
  inkSlotFamilyForTool,
  INK_PEN_FAMILY_TOOLS,
  normalizeEraserMode,
  type EraserPreset,
  type GesturePreferences,
  type InkPresetStoreOptions,
  type InkPresetToolId,
  type InkSlotFamily,
  type InkToolPreferencesV1,
  type InkToolPreset,
  type LineArrowSetting,
  type LassoPreset,
  type SurfaceToolPresetState,
} from './ink/presets.js';
export {
  SURFACE_STYLE_LIBRARY_VERSION,
  SurfaceStyleLibrary,
  type SurfaceStyleLibraryState,
  type SurfaceStylePreset,
} from './ink/style-library.js';
export {
  GESTURE_THRESHOLDS,
  recognizeArrow,
  recognizeCircle,
  recognizeEllipse,
  recognizeLine,
  recognizeRectangle,
  recognizeScribble,
  recognizeShape,
  type ArrowFit,
  type CircleHit,
  type EllipseFit,
  type LineFit,
  type RectFit,
  type ScribbleHit,
  type ShapeFit,
} from './ink/gestures.js';
export { inkPageKind, inkPageKindId } from './kind.js';

export { selectionHandles } from './selection.js';

export { observeSurfaceTransactions, publishSurfaceObjects, applySurfaceOrderEdits, type SurfaceOrderEdit } from './transactions.js';
