export {
  NOTEBOOK_FORMAT_VERSION,
  NOTEBOOK_DEFAULT_PAGE_WIDTH,
  NOTEBOOK_DEFAULT_PAGE_HEIGHT,
  emptyNotebook,
  notebookPage,
  pdfNotebookPage,
  appendPage,
  isNavigablePage,
  navigablePageIds,
  labelOf,
  baseOf,
  templateOf,
  paperOptionsOf,
  setPaperOptions,
  setPageLabel,
  setPageTemplate,
  type NotebookModel,
  type NotebookMeta,
  type NotebookPage,
  type NotebookPageEntry,
  type NotebookPageId,
  type NotebookPageOptions,
  type PdfNotebookPageOptions,
  type NotebookPageBase,
  type TemplateNotebookPageBase,
  type PdfNotebookPageBase,
  type NotebookPageBox,
  type OpaqueNotebookPage,
} from './model.js';
export {
  isValidPaperOptions,
  normalizePaperOptions,
  resolvePaperColor,
  resolvePaperSpacing,
  pageSizePreset,
  orientSize,
  orientationOf,
  PAPER_SPACING_MIN,
  PAPER_SPACING_MAX,
  PAPER_COLOR_MAX_LENGTH,
  NOTEBOOK_PAGE_SIZES,
  NOTEBOOK_PAGE_SIZE_IDS,
  type NotebookPaperOptions,
  type NotebookPageSizeId,
  type NotebookPageOrientation,
  type NotebookPageDimensions,
} from './paper.js';
export {
  canonicalNotebookJson,
  decodeNotebook,
  encodeNotebook,
  NOTEBOOK_LIMITS,
  type DecodeNotebookResult,
  type NotebookWarning,
  type NotebookWarningCode,
} from './codec.js';
export { notebookKind, notebookKindId } from './kind.js';
export { projectNotebookForSearch, type NotebookSearchAnchor, type NotebookSearchProjection } from './search.js';
export { extractNotebookMetadata } from './metadata.js';
